sudo: required
language: python
python:
  - 3.5
  - 3.6
env:
  global:
    - NO_SLOW=true
  matrix:
    - PANDAS_VERSION=0.19 NUMPY_VERSION=1.12
    - PANDAS_VERSION=0.20 NUMPY_VERSION=1.13
    - PANDAS_VERSION=0.21 NUMPY_VERSION=1.13
    - PANDAS_VERSION=0.22 NUMPY_VERSION=1.14 NO_SLOW=false

cache:
  directories:
    - $HOME/miniconda3 # miniconda cache

# Setup miniconda
before_install:
  - export PATH=$HOME/miniconda3/bin:$PATH
  - ci/before_install_travis.sh

# command to install dependencies
install:
  - conda install -n sksurv-test -c sebp --file requirements.txt
  - source activate sksurv-test
  - pip install --disable-pip-version-check --upgrade pip
  - python setup.py sdist
  - pip install --pre --no-index --find-links dist/ scikit-survival
  - rm -fr sksurv

# command to run tests
script: ci/run_tests.sh

after_success:
  - ci/submit_coverage.sh
